### ISSUE TITLE
return current status?

### ISSUE THREAD

**Issue by derailius** [Vaiz/HdrSwitcher#1]
First of all, I spent two hours (give or take) looking for this exact tool. So a HUGE thank you for that. I do have one suggestion, though. As the title states, it would be nice if when you simply run the app without an argument or flag that it return the current state of your display. A simple return of HDR or SDR would suffice. This will allow us nerds to use the information in our automations. Thanks again!

**Comment by Vaiz** [comment]
Hi Deralilius, it's great to hear that someone else is using this tool! 

I can add the requested functionality, but I don't want to change the default behavior. Instead, I can add a new 'status' subcommand. Will it work for you?

Example:
> HdrSwitcher.exe status
HDR
>

**Comment by derailius** [comment]
oh of course, that's perfect, and thank you!

**Comment by Vaiz** [comment]
I've added the command, feel free to test it: [HdrSwitcher.zip](https://github.com/Vaiz/HdrSwitcher/files/14156374/HdrSwitcher.zip)
I'll update the main branch later. 

I also discovered that some antiviruses may flag my binary as suspicious, so please be cautious :). To avoid any potential risks, you can compile the new version from the  [status_cmd](https://github.com/Vaiz/HdrSwitcher/tree/status_cmd) branch.
One more thing to know is that this application should not require administrative privileges to work.

https://www.virustotal.com/gui/file/d330d8cd71619b62f585be0d12e85793cfd48aac0ea805b0a04cf3c52c76398b/detection
