### ISSUE TITLE
A problem with "toggle"

### ISSUE THREAD

**Issue by UzverUA** [Vaiz/HdrSwitcher#4]
Hi. Great app! But I have a problem with "toggle". 
HdrSwitcher.exe toggle --name "LG TV SSCR2" this command can disable hdr, but doesn't enable it. 
When I use this command when HDR is disabled, it says "HDR is disabled for display with id 4352" and does nothing. 
![{E3656AF7-83E6-4D12-A557-CE21EA6B2419}](https://github.com/user-attachments/assets/ca0aa33b-70b1-4cca-8a19-bc400ec674db)

On screenshot. "enable" enables hdr, "disable" disables hdr, but toggle does nothing.

**Comment by Vaiz** [comment]
@UzverUA, thanks for the report. 
Could you share more information about your setup? The output from `HdrSwitcher.exe list` should be enough

**Comment by UzverUA** [comment]
Of course. Here you go ![image](https://github.com/user-attachments/assets/2a1cec49-91d7-44e2-b333-e65ddac2ba11)
Both other displays have hdr too
And I tried to toggle now once more as well with no luck.

**Comment by Vaiz** [comment]
I tried to reproduce the problem to no avail. I also didn't find any issues in the source code.
However, I did some refactoring which might help -  [PR](https://github.com/Vaiz/HdrSwitcher/pull/5/files). Could you try the new version and see if it helps?

[HdrSwitcher 1.3.zip](https://github.com/user-attachments/files/18218698/HdrSwitcher.zip)

**Comment by UzverUA** [comment]
![image](https://github.com/user-attachments/assets/4fe9fc46-66fd-4a73-bc1e-f119e72345c3)
Sorry for delay. I tested it, Above red line tried with all monitors connected. Same as always. Below line - disconnected all monitors but one.

It just always sees it with HDR enabled when HDR is clearly disabled in windows display settings.  Looks like getting HDR state from TVs works in a different way or doesn't work at all. Because it shows that my other HDR-capable monitors in SDR which is correct

**Comment by UzverUA** [comment]
I tried to get that info myself. And got same results. But with help from ChatGPT it figured out the way it could be done by analyzing source code of  https://github.com/res2k/HDRTray/ where it was getting correct HDR state of TV. So the key thing is that there is a new function to get display info. Chat says that it was added in 24H2, but I used that app in 23H* so yeah) 
In code below it uses that new function, and if it returns error code it falls back on "old" function. And everything works like a charm. Unsupported for both monitors on screenshot means that my other monitors don't support HDR because I deleted metadata using CRU tool. 

![image](https://github.com/user-attachments/assets/8cbda8b0-e70b-411c-b163-95f156223ca1)

So there's possibility that this could be a solution. 
I don't know if all enum codes is set correctly by chat, because I had to change DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO_2 from 13 to 15 for "a new function" to work, so maybe there's more mistakes. Can't figure out because it's too overwhelming for me:) 

So if you someday will have right mood and some free time, maybe you can check this out? If everything works for ya it's perfectly fine to skip this. I'm basically halfway done to make that hdr toggle myself))) 

Can't figure out how to paste code here in compact way, so here's link to pastebin https://pastebin.com/8BCHwCyD

**Comment by Vaiz** [comment]
Thanks for research! I'll take a look into this new API

**Comment by Vaiz** [comment]
@UzverUA , I just made a prototype based on your research. Could you try it?

[HdrSwitcher.zip](https://github.com/user-attachments/files/18222980/HdrSwitcher.zip)

**Comment by UzverUA** [comment]
Sorry for delays. Here's output. 
![image](https://github.com/user-attachments/assets/cff13133-9144-44aa-9b66-bc1897975e74)

**Comment by UzverUA** [comment]
And output of the code from pastebin at the same conditions.
![image](https://github.com/user-attachments/assets/3ecf87da-55b5-4e6e-9a6c-6dc6092e93ce)

**Comment by Vaiz** [comment]
Interesting, I guess `DISPLAYCONFIG_ADVANCED_COLOR_MODE_WCG` doesn't mean HDR although the description is similar
```C
typedef enum _DISPLAYCONFIG_ADVANCED_COLOR_MODE
{
    DISPLAYCONFIG_ADVANCED_COLOR_MODE_SDR,          // RGB888 composition, display-referred color, display-referred luminance
    DISPLAYCONFIG_ADVANCED_COLOR_MODE_WCG,          // Advanced color (FP16 scRGB composition), scene-referred color, display-referred luminance
    DISPLAYCONFIG_ADVANCED_COLOR_MODE_HDR,          // Advanced color (FP16 scRGB composition), scene-referred color, scene-referred luminance
} DISPLAYCONFIG_ADVANCED_COLOR_MODE;
```

**Comment by UzverUA** [comment]
Yeah, I guess it's still DISPLAYCONFIG_ADVANCED_COLOR_MODE_HDR but only difference is that now it should work:) 
Going offline...

**Comment by Vaiz** [comment]
Thanks for your help! 
In the latest version, DISPLAYCONFIG_ADVANCED_COLOR_MODE_WCG counts as SDR which seems to be your case

[HdrSwitcher.zip](https://github.com/user-attachments/files/18223072/HdrSwitcher.zip)

**Comment by UzverUA** [comment]
![image](https://github.com/user-attachments/assets/c959e1ea-3362-41ff-bc43-aed66cab5638)
All thanks to you!

**Comment by Vaiz** [comment]
Once again, thanks for your help :)
If there are no further changes, I will release this as the final version by the end of the week
[HdrSwitcher.zip](https://github.com/user-attachments/files/18227451/HdrSwitcher.zip)

**Comment by UzverUA** [comment]
As good as it gets:) Thanks! I really appreciate it. Literally, it's the only app where you can change HDR state of specific display with no extra hustle like deleting displays metadata in CRU that resets all the time)) 
Have an awesome day!)
